Repository cleder/fastkml, pull requests merged in 2024-12, with the labels that each got.

#397 396 kml model
  README.rst
  _typos.toml
  docs/HISTORY.rst
  docs/fastkml.rst
  docs/working_with_kml.rst
  fastkml/containers.py
  fastkml/data.py
  fastkml/features.py
  fastkml/geometry.py
  fastkml/kml.py
  fastkml/links.py
  fastkml/model.py
  fastkml/overlays.py
  fastkml/styles.py
  fastkml/views.py
  tests/hypothesis/feature_test.py
  tests/hypothesis/model_test.py
  tests/model_test.py
  tests/overlays_test.py
Labels: Review effort [1-5]: 3

#392 Network LInk Control
  docs/network.kml
  fastkml/__init__.py
  fastkml/kml.py
  fastkml/network_link_control.py
  tests/network_link_control_test.py
Labels: Review effort [1-5]: 3

#398 390 network link control
  docs/HISTORY.rst
  docs/network.kml
  fastkml/__init__.py
  fastkml/kml.py
  fastkml/network_link_control.py
  tests/hypothesis/network_link_control_test.py
  tests/network_link_control_test.py
Labels: Review effort [1-5]: 2

#400 Version 1.1
  .pre-commit-config.yaml
  README.rst
  _typos.toml
  docs/HISTORY.rst
  docs/Makefile
  docs/conf.py
  docs/create_kml_files.rst
  docs/fastkml.rst
  docs/index.rst
  docs/kml.rst
  docs/network.kml
  docs/quickstart.rst
  docs/upgrading.rst
  docs/working_with_kml.rst
  examples/owid-co2-data.csv
  examples/shp2kml.py
  examples/shp2kml_timed.py
  examples/simple_example.py
  fastkml/__init__.py
  fastkml/about.py
  fastkml/base.py
  fastkml/containers.py
  fastkml/data.py
  fastkml/features.py
  fastkml/geometry.py
  fastkml/kml.py
  fastkml/links.py
  fastkml/model.py
  fastkml/network_link_control.py
  fastkml/overlays.py
  fastkml/registry.py
  fastkml/styles.py
  fastkml/times.py
  fastkml/views.py
  pyproject.toml
  tests/hypothesis/feature_test.py
  tests/hypothesis/model_test.py
  tests/hypothesis/network_link_control_test.py
  tests/hypothesis/overlay_test.py
  tests/hypothesis/strategies.py
  tests/model_test.py
  tests/network_link_control_test.py
  tests/overlays_test.py
Labels: Review effort [1-5]: 4
